package com.example.techmain.firebase

object QuestionBank {
    data class Category(val id: String, val name: String, val icon: String)

    val categories = listOf(
        Category("math", "Matematika", "calculate"),
        Category("science", "IPA", "biotech"),
        Category("history", "Sejarah", "history"),
        Category("geography", "Geografi", "public"),
        Category("language", "Bahasa", "translate"),
        Category("general", "Pengetahuan Umum", "lightbulb")
    )

    fun getQuestions(categoryId: String): List<QuizQuestion> {
        return when (categoryId) {
            "math" -> listOf(
                QuizQuestion(id = "m1", categoryId = "math", question = "Berapa hasil dari 25 × 4?", options = listOf("75", "100", "125", "150"), correctAnswer = 1),
                QuizQuestion(id = "m2", categoryId = "math", question = "Akar kuadrat dari 144 adalah?", options = listOf("10", "11", "12", "13"), correctAnswer = 2),
                QuizQuestion(id = "m3", categoryId = "math", question = "Berapa hasil dari ⅓ + ⅙?", options = listOf("¼", "⅓", "½", "⅔"), correctAnswer = 2),
                QuizQuestion(id = "m4", categoryId = "math", question = "Jika x + 5 = 12, berapa nilai x?", options = listOf("5", "6", "7", "8"), correctAnswer = 2),
                QuizQuestion(id = "m5", categoryId = "math", question = "Berapa luas lingkaran dengan jari-jari 7 cm? (π = 22/7)", options = listOf("144 cm²", "154 cm²", "164 cm²", "174 cm²"), correctAnswer = 1),
                QuizQuestion(id = "m6", categoryId = "math", question = "45% dari 200 adalah?", options = listOf("70", "80", "90", "100"), correctAnswer = 2),
                QuizQuestion(id = "m7", categoryId = "math", question = "Berapa sisi yang dimiliki kubus?", options = listOf("4", "6", "8", "12"), correctAnswer = 1),
                QuizQuestion(id = "m8", categoryId = "math", question = "Hasil dari (-3) × (-4) adalah?", options = listOf("-12", "-7", "7", "12"), correctAnswer = 3),
                QuizQuestion(id = "m9", categoryId = "math", question = "Berapa hasil dari 10 + 15 × 2?", options = listOf("50", "40", "35", "30"), correctAnswer = 1),
                QuizQuestion(id = "m10", categoryId = "math", question = "Berapa jumlah sudut dalam sebuah segitiga?", options = listOf("90°", "180°", "270°", "360°"), correctAnswer = 1),
                QuizQuestion(id = "m11", categoryId = "math", question = "Berapa volume kubus dengan panjang rusuk 5 cm?", options = listOf("25 cm³", "75 cm³", "100 cm³", "125 cm³"), correctAnswer = 3),
                QuizQuestion(id = "m12", categoryId = "math", question = "Jika sebuah dadu dilempar, berapa peluang munculnya angka genap?", options = listOf("1/6", "1/3", "1/2", "2/3"), correctAnswer = 2),
                QuizQuestion(id = "m13", categoryId = "math", question = "Berapa hasil dari 2 pangkat 5 (2⁵)?", options = listOf("10", "16", "32", "64"), correctAnswer = 2),
                QuizQuestion(id = "m14", categoryId = "math", question = "Faktor Persekutuan Terbesar (FPB) dari 12 dan 18 adalah?", options = listOf("2", "3", "4", "6"), correctAnswer = 3),
                QuizQuestion(id = "m15", categoryId = "math", question = "Kelipatan Persekutuan Terkecil (KPK) dari 4 dan 6 adalah?", options = listOf("12", "18", "24", "36"), correctAnswer = 0),
                QuizQuestion(id = "m16", categoryId = "math", question = "Berapa hasil dari 150 - 25 × 4?", options = listOf("500", "100", "50", "0"), correctAnswer = 2),
                QuizQuestion(id = "m17", categoryId = "math", question = "Sebuah persegi memiliki keliling 24 cm. Berapa panjang sisinya?", options = listOf("4 cm", "6 cm", "8 cm", "12 cm"), correctAnswer = 1),
                QuizQuestion(id = "m18", categoryId = "math", question = "Berapa nilai dari sudut siku-siku?", options = listOf("45°", "90°", "180°", "360°"), correctAnswer = 1),
                QuizQuestion(id = "m19", categoryId = "math", question = "Berapa hasil dari 900 ÷ 30?", options = listOf("3", "20", "30", "300"), correctAnswer = 2),
                QuizQuestion(id = "m20", categoryId = "math", question = "Berapakah nilai rata-rata dari bilangan 4, 6, 8, dan 10?", options = listOf("6", "7", "8", "9"), correctAnswer = 1),
            )
            "science" -> listOf(
                QuizQuestion(id = "s1", categoryId = "science", question = "Apa planet terbesar di tata surya?", options = listOf("Saturnus", "Jupiter", "Neptunus", "Uranus"), correctAnswer = 1),
                QuizQuestion(id = "s2", categoryId = "science", question = "Apa simbol kimia untuk air?", options = listOf("H2O", "CO2", "NaCl", "O2"), correctAnswer = 0),
                QuizQuestion(id = "s3", categoryId = "science", question = "Berapa jumlah tulang manusia dewasa?", options = listOf("106", "206", "306", "406"), correctAnswer = 1),
                QuizQuestion(id = "s4", categoryId = "science", question = "Apa gas yang paling banyak di atmosfer bumi?", options = listOf("Oksigen", "Karbon dioksida", "Nitrogen", "Hidrogen"), correctAnswer = 2),
                QuizQuestion(id = "s5", categoryId = "science", question = "Fotosintesis menghasilkan?", options = listOf("CO2 dan Air", "Oksigen dan Glukosa", "Nitrogen dan Protein", "Karbon dan Mineral"), correctAnswer = 1),
                QuizQuestion(id = "s6", categoryId = "science", question = "Berapa kecepatan cahaya per detik?", options = listOf("100.000 km", "200.000 km", "300.000 km", "400.000 km"), correctAnswer = 2),
                QuizQuestion(id = "s7", categoryId = "science", question = "Apa organ terbesar dalam tubuh manusia?", options = listOf("Hati", "Paru-paru", "Kulit", "Otak"), correctAnswer = 2),
                QuizQuestion(id = "s8", categoryId = "science", question = "Apa nama proses perubahan air menjadi uap?", options = listOf("Kondensasi", "Evaporasi", "Presipitasi", "Sublimasi"), correctAnswer = 1),
                QuizQuestion(id = "s9", categoryId = "science", question = "Apa planet terdekat dari matahari?", options = listOf("Venus", "Merkurius", "Bumi", "Mars"), correctAnswer = 1),
                QuizQuestion(id = "s10", categoryId = "science", question = "Zat hijau daun pada tumbuhan disebut?", options = listOf("Kloroplas", "Klorofil", "Stomata", "Sitoplasma"), correctAnswer = 1),
                QuizQuestion(id = "s11", categoryId = "science", question = "Hewan yang memakan tumbuhan saja disebut?", options = listOf("Karnivora", "Herbivora", "Omnivora", "Insektivora"), correctAnswer = 1),
                QuizQuestion(id = "s12", categoryId = "science", question = "Suhu di mana air murni membeku adalah?", options = listOf("-10°C", "0°C", "32°C", "100°C"), correctAnswer = 1),
                QuizQuestion(id = "s13", categoryId = "science", question = "Gaya yang menarik benda ke pusat bumi disebut gaya?", options = listOf("Magnet", "Gesek", "Pegas", "Gravitasi"), correctAnswer = 3),
                QuizQuestion(id = "s14", categoryId = "science", question = "Bagian sel darah yang berfungsi mengangkut oksigen adalah?", options = listOf("Sel darah merah", "Sel darah putih", "Keping darah", "Plasma darah"), correctAnswer = 0),
                QuizQuestion(id = "s15", categoryId = "science", question = "Energi yang dihasilkan oleh pergerakan elektron disebut?", options = listOf("Energi panas", "Energi kimia", "Energi listrik", "Energi bunyi"), correctAnswer = 2),
                QuizQuestion(id = "s16", categoryId = "science", question = "Bunyi tidak dapat merambat melalui ruang?", options = listOf("Udara", "Air", "Hampa", "Padat"), correctAnswer = 2),
                QuizQuestion(id = "s17", categoryId = "science", question = "Alat indra manusia yang mendeteksi perubahan suhu dan tekanan adalah?", options = listOf("Mata", "Telinga", "Kulit", "Hidung"), correctAnswer = 2),
                QuizQuestion(id = "s18", categoryId = "science", question = "Perubahan wujud benda padat langsung menjadi gas dinamakan?", options = listOf("Mencair", "Menghablur", "Menyublim", "Menguap"), correctAnswer = 2),
                QuizQuestion(id = "s19", categoryId = "science", question = "Lensa mata yang mengalami kekeruhan sehingga mengganggu penglihatan disebut penyakit?", options = listOf("Miopi", "Katarak", "Silindris", "Glaukoma"), correctAnswer = 1),
                QuizQuestion(id = "s20", categoryId = "science", question = "Lapisan terluar bumi tempat manusia tinggal dinamakan?", options = listOf("Inti dalam", "Inti luar", "Mantel bumi", "Kerak bumi"), correctAnswer = 3),
            )
            "history" -> listOf(
                QuizQuestion(id = "h1", categoryId = "history", question = "Tahun berapa Indonesia merdeka?", options = listOf("1942", "1945", "1949", "1950"), correctAnswer = 1),
                QuizQuestion(id = "h2", categoryId = "history", question = "Siapa presiden pertama Indonesia?", options = listOf("Soeharto", "Soekarno", "Hatta", "Sutan Syahrir"), correctAnswer = 1),
                QuizQuestion(id = "h3", categoryId = "history", question = "Perang Dunia II berakhir tahun?", options = listOf("1943", "1944", "1945", "1946"), correctAnswer = 2),
                QuizQuestion(id = "h4", categoryId = "history", question = "Siapa yang menemukan benua Amerika?", options = listOf("Vasco da Gama", "Ferdinand Magellan", "Christopher Columbus", "Marco Polo"), correctAnswer = 2),
                QuizQuestion(id = "h5", categoryId = "history", question = "Candi Borobudur terletak di provinsi?", options = listOf("Jawa Barat", "Jawa Tengah", "Jawa Timur", "Yogyakarta"), correctAnswer = 1),
                QuizQuestion(id = "h6", categoryId = "history", question = "Tembok Besar Cina dibangun pada dinasti?", options = listOf("Ming", "Qin", "Tang", "Song"), correctAnswer = 1),
                QuizQuestion(id = "h7", categoryId = "history", question = "Apa nama kerajaan Hindu pertama di Indonesia?", options = listOf("Majapahit", "Sriwijaya", "Kutai", "Singhasari"), correctAnswer = 2),
                QuizQuestion(id = "h8", categoryId = "history", question = "Siapa pahlawan nasional dari Aceh?", options = listOf("Diponegoro", "Cut Nyak Dhien", "Imam Bonjol", "Pattimura"), correctAnswer = 1),
                QuizQuestion(id = "h9", categoryId = "history", question = "Siapa pencipta lagu kebangsaan Indonesia Raya?", options = listOf("Ibu Sud", "Ismail Marzuki", "W.R. Supratman", "Kusbini"), correctAnswer = 2),
                QuizQuestion(id = "h10", categoryId = "history", question = "Negara mana yang menjajah Indonesia paling lama?", options = listOf("Jepang", "Belanda", "Inggris", "Portugis"), correctAnswer = 1),
                QuizQuestion(id = "h11", categoryId = "history", question = "Di kota manakah naskah proklamasi kemerdekaan Indonesia dirumuskan?", options = listOf("Bandung", "Yogyakarta", "Jakarta", "Surabaya"), correctAnswer = 2),
                QuizQuestion(id = "h12", categoryId = "history", question = "Siapa tokoh yang menjabat sebagai Wakil Presiden Indonesia pertama?", options = listOf("Moh. Hatta", "Adam Malik", "Sudharmono", "Ki Hajar Dewantara"), correctAnswer = 0),
                QuizQuestion(id = "h13", categoryId = "history", question = "Peristiwa penculikan Soekarno-Hatta ke luar kota menjelang proklamasi dikenal sebagai peristiwa?", options = listOf("Ambarawa", "Rengasdengklok", "Boedi Oetomo", "G30S"), correctAnswer = 1),
                QuizQuestion(id = "h14", categoryId = "history", question = "Kerajaan Islam pertama di pulau Jawa adalah?", options = listOf("Demak", "Banten", "Mataram", "Cirebon"), correctAnswer = 0),
                QuizQuestion(id = "h15", categoryId = "history", question = "Sumpah Palapa yang terkenal diucapkan oleh patih terkenal bernama?", options = listOf("Ken Arok", "Gajah Mada", "Kertanegara", "Raden Wijaya"), correctAnswer = 1),
                QuizQuestion(id = "h16", categoryId = "history", question = "Organisasi pergerakan nasional pertama di Indonesia adalah?", options = listOf("Sarekat Islam", "Indische Partij", "Budi Utomo", "PNI"), correctAnswer = 2),
                QuizQuestion(id = "h17", categoryId = "history", question = "Siapakah raja terkenal dari kerajaan Singasari?", options = listOf("Mulawarman", "Purnawarman", "Hayam Wuruk", "Kertanegara"), correctAnswer = 3),
                QuizQuestion(id = "h18", categoryId = "history", question = "Kapan peristiwa Sumpah Pemuda dicetuskan?", options = listOf("17 Agustus 1945", "28 Oktober 1928", "20 Mei 1908", "10 November 1945"), correctAnswer = 1),
                QuizQuestion(id = "h19", categoryId = "history", question = "Siapa laksamana Jepang yang menyediakan rumahnya untuk perumusan teks proklamasi?", options = listOf("Yamamoto", "Maeda", "Tojo", "Hirohito"), correctAnswer = 1),
                QuizQuestion(id = "h20", categoryId = "history", question = "Kota di Jepang yang pertama kali dijatuhi bom atom oleh Sekutu adalah?", options = listOf("Tokyo", "Kyoto", "Nagasaki", "Hiroshima"), correctAnswer = 3),
            )
            "geography" -> listOf(
                QuizQuestion(id = "g1", categoryId = "geography", question = "Apa ibu kota Indonesia?", options = listOf("Surabaya", "Bandung", "Jakarta", "Yogyakarta"), correctAnswer = 2),
                QuizQuestion(id = "g2", categoryId = "geography", question = "Gunung tertinggi di dunia adalah?", options = listOf("Kilimanjaro", "Everest", "Elbrus", "Aconcagua"), correctAnswer = 1),
                QuizQuestion(id = "g3", categoryId = "geography", question = "Sungai terpanjang di dunia?", options = listOf("Amazon", "Nil", "Mississippi", "Yangtze"), correctAnswer = 1),
                QuizQuestion(id = "g4", categoryId = "geography", question = "Berapa jumlah provinsi di Indonesia saat ini?", options = listOf("34", "37", "38", "40"), correctAnswer = 2),
                QuizQuestion(id = "g5", categoryId = "geography", question = "Benua terluas di dunia?", options = listOf("Afrika", "Amerika Utara", "Asia", "Eropa"), correctAnswer = 2),
                QuizQuestion(id = "g6", categoryId = "geography", question = "Laut terluas di dunia?", options = listOf("Atlantik", "Pasifik", "Hindia", "Arktik"), correctAnswer = 1),
                QuizQuestion(id = "g7", categoryId = "geography", question = "Negara dengan populasi terbanyak di dunia?", options = listOf("India", "Cina", "AS", "Indonesia"), correctAnswer = 0),
                QuizQuestion(id = "g8", categoryId = "geography", question = "Gurun terluas di dunia?", options = listOf("Gobi", "Sahara", "Kalahari", "Arab"), correctAnswer = 1),
                QuizQuestion(id = "g9", categoryId = "geography", question = "Apa nama selat yang memisahkan pulau Jawa dan Sumatra?", options = listOf("Selat Sunda", "Selat Malaka", "Selat Bali", "Selat Makassar"), correctAnswer = 0),
                QuizQuestion(id = "g10", categoryId = "geography", question = "Negara terkecil di dunia adalah?", options = listOf("Monako", "San Marino", "Vatikan", "Maladewa"), correctAnswer = 2),
                QuizQuestion(id = "g11", categoryId = "geography", question = "Garis khayal yang membagi bumi menjadi belahan utara dan selatan disebut?", options = listOf("Garis Bujur", "Garis Khatulistiwa", "Garis Meridian", "Garis Balik"), correctAnswer = 1),
                QuizQuestion(id = "g12", categoryId = "geography", question = "Benua yang terkecil di dunia adalah?", options = listOf("Eropa", "Antartika", "Australia", "Amerika Selatan"), correctAnswer = 2),
                QuizQuestion(id = "g13", categoryId = "geography", question = "Samudra terdalam di dunia adalah?", options = listOf("Samudra Hindia", "Samudra Atlantik", "Samudra Pasifik", "Samudra Arktik"), correctAnswer = 2),
                QuizQuestion(id = "g14", categoryId = "geography", question = "Danau vulkanik terbesar di Indonesia adalah?", options = listOf("Danau Toba", "Danau Singkarak", "Danau Poso", "Danau Batur"), correctAnswer = 0),
                QuizQuestion(id = "g15", categoryId = "geography", question = "Negara mana yang terkenal dengan julukan Negeri Kincir Angin?", options = listOf("Jerman", "Inggris", "Belanda", "Prancis"), correctAnswer = 2),
                QuizQuestion(id = "g16", categoryId = "geography", question = "Pulau terbesar di wilayah negara Indonesia adalah?", options = listOf("Jawa", "Sumatra", "Kalimantan", "Sulawesi"), correctAnswer = 2),
                QuizQuestion(id = "g17", categoryId = "geography", question = "Secara astronomis, Indonesia terletak di antara dua benua yaitu?", options = listOf("Asia dan Australia", "Asia dan Eropa", "Amerika dan Afrika", "Asia dan Amerika"), correctAnswer = 0),
                QuizQuestion(id = "g18", categoryId = "geography", question = "Gunung berapi tertinggi yang masih aktif di Indonesia adalah?", options = listOf("Gunung Merapi", "Gunung Semeru", "Gunung Kerinci", "Gunung Agung"), correctAnswer = 2),
                QuizQuestion(id = "g19", categoryId = "geography", question = "Ibu kota dari negara Jepang adalah?", options = listOf("Kyoto", "Osaka", "Hiroshima", "Tokyo"), correctAnswer = 3),
                QuizQuestion(id = "g20", categoryId = "geography", question = "Mata uang resmi yang digunakan di negara Malaysia adalah?", options = listOf("Dolar", "Peso", "Baht", "Ringgit"), correctAnswer = 3),
            )
            "language" -> listOf(
                QuizQuestion(id = "l1", categoryId = "language", question = "\"Good morning\" dalam bahasa Indonesia adalah?", options = listOf("Selamat sore", "Selamat pagi", "Selamat malam", "Selamat siang"), correctAnswer = 1),
                QuizQuestion(id = "l2", categoryId = "language", question = "Sinonim dari \"cerdas\" adalah?", options = listOf("Bodoh", "Pandai", "Malas", "Lemah"), correctAnswer = 1),
                QuizQuestion(id = "l3", categoryId = "language", question = "Bahasa resmi negara Brasil adalah?", options = listOf("Spanyol", "Portugis", "Inggris", "Prancis"), correctAnswer = 1),
                QuizQuestion(id = "l4", categoryId = "language", question = "Antonim dari \"besar\" adalah?", options = listOf("Lebar", "Panjang", "Kecil", "Tinggi"), correctAnswer = 2),
                QuizQuestion(id = "l5", categoryId = "language", question = "Apa arti \"pulchritudinous\"?", options = listOf("Cepat", "Indah", "Kuat", "Tua"), correctAnswer = 1),
                QuizQuestion(id = "l6", categoryId = "language", question = "Bahasa apa yang paling banyak digunakan di dunia?", options = listOf("Inggris", "Mandarin", "Spanyol", "Hindi"), correctAnswer = 1),
                QuizQuestion(id = "l7", categoryId = "language", question = "Kata \"demokrasi\" berasal dari bahasa?", options = listOf("Latin", "Yunani", "Inggris", "Arab"), correctAnswer = 1),
                QuizQuestion(id = "l8", categoryId = "language", question = "Apa imbuhan yang menunjukkan \"telah melakukan\"?", options = listOf("Me-", "Ber-", "Ter-", "Di-"), correctAnswer = 2),
                QuizQuestion(id = "l9", categoryId = "language", question = "Kata dasar dari 'mempertanggungjawabkan' adalah?", options = listOf("Tanggung", "Tanggung jawab", "Pertanggung", "Jawab"), correctAnswer = 1),
                QuizQuestion(id = "l10", categoryId = "language", question = "Bahasa Inggris dari 'perpustakaan' adalah?", options = listOf("Classroom", "Laboratory", "Library", "Office"), correctAnswer = 2),
                QuizQuestion(id = "l11", categoryId = "language", question = "Manakah penulisan kata baku yang benar menurut KBBI?", options = listOf("Apotik", "Apotek", "Apotech", "Apoteg"), correctAnswer = 1),
                QuizQuestion(id = "l12", categoryId = "language", question = "Kalimat yang memiliki subjek dan predikat yang jelas disebut kalimat?", options = listOf("Pasif", "Aktif", "Efektif", "Tanya"), correctAnswer = 2),
                QuizQuestion(id = "l13", categoryId = "language", question = "Gaya bahasa yang menggunakan perbandingan kiasan langsung disebut majas?", options = listOf("Hiperbola", "Metafora", "Personifikasi", "Ironi"), correctAnswer = 1),
                QuizQuestion(id = "l14", categoryId = "language", question = "Antonim dari kata 'khawatir' adalah?", options = listOf("Cemas", "Takut", "Tenang", "Gelisah"), correctAnswer = 2),
                QuizQuestion(id = "l15", categoryId = "language", question = "Sinonim dari kata 'kamuflase' adalah?", options = listOf("Penyamaran", "Keterbukaan", "Keaslian", "Pamer"), correctAnswer = 0),
                QuizQuestion(id = "l16", categoryId = "language", question = "Huruf kapital digunakan pada awal kata untuk nama?", options = listOf("Buah", "Hari", "Hewan", "Warna"), correctAnswer = 1),
                QuizQuestion(id = "l17", categoryId = "language", question = "Kata 'tertidur' menggunakan imbuhan 'ter-' yang bermakna?", options = listOf("Paling", "Sengaja", "Tidak sengaja", "Banyak"), correctAnswer = 2),
                QuizQuestion(id = "l18", categoryId = "language", question = "Tanda baca yang digunakan untuk mengakhiri kalimat berita adalah?", options = listOf("Koma", "Titik dua", "Tanda seru", "Titik"), correctAnswer = 3),
                QuizQuestion(id = "l19", categoryId = "language", question = "Berikut ini yang termasuk kata depan adalah?", options = listOf("Dan", "Tetapi", "Di", "Karena"), correctAnswer = 2),
                QuizQuestion(id = "l20", categoryId = "language", question = "Karya sastra puisi lama yang terdiri dari 4 baris bersajak a-b-a-b disebut?", options = listOf("Gurindam", "Pantun", "Syair", "Prosa"), correctAnswer = 1),
            )
            else -> listOf(
                QuizQuestion(id = "u1", categoryId = "general", question = "Berapa hari dalam setahun?", options = listOf("360", "364", "365", "366"), correctAnswer = 2),
                QuizQuestion(id = "u2", categoryId = "general", question = "Apa warna bendera Indonesia?", options = listOf("Merah-Putih", "Merah-Biru", "Putih-Hijau", "Kuning-Hitam"), correctAnswer = 0),
                QuizQuestion(id = "u3", categoryId = "general", question = "Alat untuk mengukur suhu disebut?", options = listOf("Barometer", "Termometer", "Hidrometer", "Speedometer"), correctAnswer = 1),
                QuizQuestion(id = "u4", categoryId = "general", question = "Hewan apa yang dikenal sebagai \"raja hutan\"?", options = listOf("Harimau", "Singa", "Gajah", "Beruang"), correctAnswer = 1),
                QuizQuestion(id = "u5", categoryId = "general", question = "Berapa jumlah warna dalam pelangi?", options = listOf("5", "6", "7", "8"), correctAnswer = 2),
                QuizQuestion("u6", "general", "Mata uang Indonesia adalah?", listOf("Rupiah", "Dollar", "Yen", "Euro"), 0),
                QuizQuestion(id = "u7", categoryId = "general", question = "Olahraga sepak bola dimainkan oleh berapa pemain per tim?", options = listOf("9", "10", "11", "12"), correctAnswer = 2),
                QuizQuestion(id = "u8", categoryId = "general", question = "Planet apa yang dikenal sebagai \"Bintang Fajar\"?", options = listOf("Mars", "Venus", "Merkurius", "Jupiter"), correctAnswer = 1),
                QuizQuestion(id = "u9", categoryId = "general", question = "Berapa tahun Indonesia merayakan satu dekade?", options = listOf("5 tahun", "10 tahun", "25 tahun", "100 tahun"), correctAnswer = 1),
                QuizQuestion(id = "u10", categoryId = "general", question = "Vitamin apa yang banyak terkandung dalam buah jeruk?", options = listOf("Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"), correctAnswer = 2),
                QuizQuestion(id = "u11", categoryId = "general", question = "Siapakah penemu lampu pijar?", options = listOf("Nikola Tesla", "Albert Einstein", "Thomas Alva Edison", "Alexander Graham Bell"), correctAnswer = 2),
                QuizQuestion(id = "u12", categoryId = "general", question = "Negara manakah yang memenangkan Piala Dunia FIFA 2022?", options = listOf("Prancis", "Brasil", "Kroasia", "Argentina"), correctAnswer = 3),
                QuizQuestion(id = "u13", categoryId = "general", question = "Mamalia laut terbesar yang masih hidup saat ini adalah?", options = listOf("Hiu Putih", "Paus Biru", "Lumba-lumba", "Anjing Laut"), correctAnswer = 1),
                QuizQuestion(id = "u14", categoryId = "general", question = "Patung Liberty yang terkenal di Amerika merupakan hadiah dari negara?", options = listOf("Inggris", "Prancis", "Spanyol", "Jerman"), correctAnswer = 1),
                QuizQuestion(id = "u15", categoryId = "general", question = "Bahan utama pembuat cokelat berasal dari biji tanaman?", options = listOf("Kopi", "Kakao", "Teh", "Kelapa"), correctAnswer = 1),
                QuizQuestion(id = "u16", categoryId = "general", question = "Menara Pisa yang miring terletak di negara?", options = listOf("Spanyol", "Prancis", "Italia", "Yunani"), correctAnswer = 2),
                QuizQuestion(id = "u17", categoryId = "general", question = "Apa nama media sosial berlambang burung biru sebelum berganti nama menjadi X?", options = listOf("Facebook", "Instagram", "Twitter", "TikTok"), correctAnswer = 2),
                QuizQuestion(id = "u18", categoryId = "general", question = "Serangga yang memproduksi madu manis dinamakan?", options = listOf("Semut", "Lebah", "Kupu-kupu", "Lalat"), correctAnswer = 1),
                QuizQuestion(id = "u19", categoryId = "general", question = "Siapa tokoh penemu jaringan internet (World Wide Web)?", options = listOf("Bill Gates", "Steve Jobs", "Tim Berners-Lee", "Mark Zuckerberg"), correctAnswer = 2),
                QuizQuestion(id = "u20", categoryId = "general", question = "Berapa jumlah tombol warna pada lampu lalu lintas jalan raya umum?", options = listOf("2", "3", "4", "5"), correctAnswer = 1),
            )
        }
    }
}